#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

PLUGIN=avr

NAME="${PLUGIN} DISasm: [0e940b10 => 0x00002016] (ANAL)"
FILE=malloc://4096
CMDS='
e asm.arch=avr
wx 0e940b10 @ 0x2d0
s 0x2d0
ao 1~jump[1]
'
EXPECT='0x00002016
'
run_test

NAME="${PLUGIN} DISasm: [0e940b10 => call] - jump check"
FILE=malloc://4096
CMDS='
e asm.arch=avr
s 0x2d0
wx 0e940b10
ao 1~jump
'
EXPECT='jump: 0x00002016
'
run_test
# /additional analyzer tests for call

NAME="${PLUGIN} DISasm: [sts] - jump check"
FILE=malloc://4096
CMDS='
e asm.arch=avr
s 0x2d0
wx 9093c007
ao 1~jump
'
EXPECT=''
run_test

# the next two is broken
NAME="${PLUGIN} DISasm: negative baddr"
BROKEN=1
FILE=../../bins/elf/analysis/bugurtos-avr.elf
ARGS=
CMDS='s 0x506
pd 2~!1
s+2
pd 1
'
EXPECT='call 0x18CE
call 0x18CE
'
run_test

NAME="${PLUGIN} DISasm: opcode size"
FILE=-
ARGS=
CMDS='e asm.arch=avr
wx 0e941122
ao~size[1]
'
EXPECT='4
'
run_test
