#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami 65535sects.exe - section list, entrypoint, open and analyze'
ARGS=''
FILE=../../bins/pe/65535sects.exe
CMDS='
aa
S~?
s
pi 1
q!
'
EXPECT='65535
0x291120
mov edi, 0x7027aff9
'
IGNORE_ERR=1
run_test
