#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami 65535sects.exe - open and analyze'
FILE=../../bins/pe/65535sects.exe
ARGS='-A'
CMDS="q!"
IGNORE_ERR=1
run_test

NAME='PE: corkami 65535sects.exe - sections list'
FILE=../../bins/pe/65535sects.exe
BROKEN=
ARGS='-n'
CMDS="!rabin2 -pS ${FILE}"
FILTER='grep sections'
EXPECT='65535 sections
'
IGNORE_ERR=1
run_test

IGNORE_ERR=
NAME='PE: corkami 65535sects.exe - entrypoint'
FILE=../../bins/pe/65535sects.exe
CMDS='
s
pi 1
'
EXPECT='0x8281120
mov edi, 0x7027aff9
'
IGNORE_ERR=1
run_test
