#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: export function names'
FILE=../../bins/pe/Lab05-01.dll
CMDS='iE'
EXPECT='[Exports]
000 0x0000cc47 0x1000d847 GLOBAL   FUNC    0 xdll.dll_InstallRT
001 0x0000d2c1 0x1000dec1 GLOBAL   FUNC    0 xdll.dll_InstallSA
002 0x0000dc92 0x1000e892 GLOBAL   FUNC    0 xdll.dll_InstallSB
003 0x00006425 0x10007025 GLOBAL   FUNC    0 xdll.dll_PSLIST
004 0x0000c330 0x1000cf30 GLOBAL   FUNC    0 xdll.dll_ServiceMain
005 0x000072cb 0x10007ecb GLOBAL   FUNC    0 xdll.dll_StartEXS
006 0x0000e805 0x1000f405 GLOBAL   FUNC    0 xdll.dll_UninstallRT
007 0x0000de05 0x1000ea05 GLOBAL   FUNC    0 xdll.dll_UninstallSA
008 0x0000e538 0x1000f138 GLOBAL   FUNC    0 xdll.dll_UninstallSB
'

run_test
