#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami imports.exe - open'
FILE=../../bins/pe/imports.exe
ARGS=''
CMDS='ii
is
?v sym.imp.msvcrt.dll_printf
'
EXPECT='[Imports]
   1 0x004010c0    NONE    FUNC kernel32.dll_ExitProcess
   1 0x004010c8    NONE    FUNC msvcrt.dll_printf
[Symbols]
001 0x000002c0 0x004010c0   NONE   FUNC    0 imp.kernel32.dll_ExitProcess
001 0x000002c8 0x004010c8   NONE   FUNC    0 imp.msvcrt.dll_printf
0x4010c8
'
run_test
