#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='dll import function names bug for ws2_32.dll'
FILE=../../bins/pe/Lab05-01.dll
CMDS='ii~&WS2_32,52
'
EXPECT='  52 0x100163cc    NONE    FUNC WS2_32.dll_gethostbyname
'
run_test
