#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami cm01.exe - open'
FILE=../../bins/pe/cm01.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='PE: corkami cm01.exe - sections'
FILE=../../bins/pe/cm01.exe
ARGS='-n'
CMDS="!rabin2 -S ${FILE}"
EXPECT='[Sections]
00 0x00000600  1536 0x00401000  4096 m-r-x CODE
01 0x00000c00   512 0x00402000  4096 m-rw- DATA
02 0x00000e00  2048 0x00403000  4096 m-rw- .idata
03 0x00001600   512 0x00404000  4096 m-r-- .edata
04 0x00001800   512 0x00405000  4096 msr-- .reloc
05 0x00001a00  5120 0x00406000  8192 msr-- .rsrc
'
run_test

NAME='PE: corkami cm01.exe - section seek 1'
FILE=../../bins/pe/cm01.exe
ARGS=''
CMDS='s 0x00401000
S.~[2]'
EXPECT='CODE
'
run_test

NAME='PE: corkami cm01.exe - section seek 2'
FILE=../../bins/pe/cm01.exe
ARGS=''
CMDS='s 0x00402000
S.~[2]'
EXPECT='DATA
'
run_test

NAME='PE: corkami cm01.exe - section seek 3'
FILE=../../bins/pe/cm01.exe
ARGS=''
CMDS='s 0x00403000
S.~[2]'
EXPECT='.idata
'
run_test

NAME='PE: corkami cm01.exe - section seek 4'
FILE=../../bins/pe/cm01.exe
ARGS=''
CMDS='s 0x00404000
S.~[2]'
EXPECT='.edata
'
run_test

NAME='PE: corkami cm01.exe - section seek 5'
FILE=../../bins/pe/cm01.exe
ARGS=''
CMDS='s 0x00405000
S.~[2]'
EXPECT='.reloc
'
run_test

NAME='PE: corkami cm01.exe - section seek 6'
FILE=../../bins/pe/cm01.exe
ARGS=''
CMDS='s 0x00406000
S.~[2]'
EXPECT='.rsrc
'
run_test

NAME='PE: corkami cm01.exe - section refs 1'
FILE=../../bins/pe/cm01.exe
ARGS=''
CMDS='e anal.strings = true
aaa
pi 2 @ 0x004010b7'
EXPECT='push str.CrackMe_v1.0
push str.No_need_to_disasm_the_code
'
run_test
 
NAME='PE: corkami cm01.exe - section refs 2'
FILE=../../bins/pe/cm01.exe
ARGS=''
CMDS='e anal.strings = true
aaa
pi 2 @ 0x0040136b'
EXPECT='push str.No_luck
push str.No_luck_there__mate
'
run_test

NAME='PE: corkami cm01.exe - section refs 3'
FILE=../../bins/pe/cm01.exe
ARGS=''
CMDS='e anal.strings = true
aaa
pi 2 @ 0x004013af'
EXPECT='push str.No_luck
push str.No_luck_there__mate
'
run_test
 
NAME='PE: corkami cm01.exe - section refs 4'
FILE=../../bins/pe/cm01.exe
ARGS=''
CMDS='e anal.strings = true
aaa
pi 2 @ 0x0040134f'
EXPECT='push str.Good_work
push str.Great_work__mate__Now_try_the_next_CrackMe
'
run_test
 
