#!/bin/sh
[ -e tests.sh ] && . ./tests.sh || . ../../tests.sh

NAME='use of dmh, then any command which use grep and index'
FILE=../../bins/elf/simple_malloc_x86_64
ARGS="-d"
CMDS='db sym.main
dc
dmh > /dev/null
aa > /dev/null
pdf @sym.main~:0
'
EXPECT='            ;-- main:
p=3
'

run_test
