#!/bin/sh

# GPL 3+ - Copyright (C) 2016 - pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='dbg.dL'
FILE=/bin/ls
ARGS=
BROKEN=
IGNORE_ERR=1
CMDS='
dL
'
EXPECT='0  ---  bf       LGPL3
1  ---  bochs    LGPL3
2  ---  esil     LGPL3
3  ---  gdb      LGPL3
4  ---  io       MIT
5  dbg  native   LGPL3
6  ---  qnx      LGPL3
7  ---  rap      LGPL3
8  ---  wind     LGPL3
'
run_test
