#!/bin/sh
# GPL 3+ - Copyright (C) 2017  rkx1209

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

# "!" - run commands (via system)

NAME='debug continue back from callee'
FILE=../../bins/elf/analysis/calls_x64
ARGS=-d
BROKEN=
CMDS='
db main
db 0x0040052f
dc
dts+
dc
dcb
dr rip
dk 9
'
EXPECT='0x00400574
'
run_test

NAME='debug continue back from caller'
FILE=../../bins/elf/analysis/calls_x64
ARGS=-d
BROKEN=
CMDS='
db main
db 0x0040057c
dc
dts+
dc
dcb
dr rip
dk 9
'
EXPECT='0x00400574
'
run_test

NAME='dbg.manycontback'
FILE=../../bins/elf/analysis/ls-linux-x86_64-zlul
ARGS=-d
BROKEN=
CMDS='
db main
db 0x004028ca
db 0x004028d1
db 0x0040290d
db 0x0040294b
dc
dts+
dc
dc
dc
dc
dcb
dr rip
dcb
dr rip
dcb
dr rip
dcb
dr rip
dk 9
'
EXPECT='0x0040290d
0x004028d1
0x004028ca
0x004028a0
'
run_test
