#!/bin/sh

# GPL 3+ - Copyright (C) 2016 - pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='dbg.px0'
FILE=/bin/ls
ARGS=
BROKEN=
IGNORE_ERR=1
CMDS='
px0
'
EXPECT='31ed4989d15e4889e24883e4f050544c8d05ca0701
'
run_test
