#!/bin/sh
# GPL 3+ - Copyright (C) 2014-2015  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='dbg.fds.count'
FILE=../../bins/elf/analysis/elf-nx
ARGS=-d
CMDS='dd~?
dk 9'
EXPECT='3
'
IGNORE_ERR=1
run_test

NAME='dbg.fds.close'
FILE=../../bins/elf/analysis/elf-nx
ARGS=-d
BROKEN=1
CMDS='dd~?
dd-1
dd~?
dk 9'
EXPECT='3
2
'
IGNORE_ERR=1
run_test

NAME='dbg.fds.count'
FILE=../../bins/elf/analysis/elf-nx
ARGS=-d
CMDS='dd~?
dk 9'
EXPECT='3
'
run_test

NAME='dd  - crash #1'
FILE='-'
CMDS='dd A'
FILTER='wc -l'
EXPECT='1
'
run_test

NAME='dd  - crash #2'
FILE='-'
CMDS='dd .,,.,,,'
FILTER='wc -l'
EXPECT='1
'
run_test

NAME='=<  - crash #1'
FILE='-'
CMDS='=< dt'
run_test

NAME='=<  - crash #2'
FILE='-'
CMDS='=<5'
run_test
