#!/bin/sh
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='rarun2 Input redirection'
SHELLCMD='rarun2 ../../bins/rr2/input_redirection.rr2 | grep -q "^foo
bar$"'
EXITCODE=0
run_test

NAME='radare2 Input redirection'
FILE='../../bins/elf/two-words'
ARGS='-r ../../bins/rr2/input_redirection.rr2 -d'
EXPECT='foo
bar
'
CMDS='
dc
'
run_test
