#!/bin/sh

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='objc hello-objc not encrypted'
BROKEN=
FILE=../../bins/mach0/hello-objc
ARGS=
CMDS='ic
'
EXPECT='0x100001180 [0x100000da0 - 0x100000e20] (sz 128) class 0 Person
0x100000da0 method 0      sayHello
0x100000df0 method 1      name
0x100000e20 method 2      setName:
'
run_test

NAME='objc generics-objc'
BROKEN=
FILE=../../bins/mach0/generics-objc
ARGS=
CMDS='ic
'
EXPECT='0x100001120 [0x100000e70 - 0x100000e70] (sz 0) class 0 MyCustomClass
0x100000e70 method 0      doSomethingWithGeneric:
'
run_test

NAME='objc method flags (ic ViewController)'
BROKEN=
FILE=../../bins/mach0/TestMethods
ARGS=
CMDS='ic ViewController
'
EXPECT='class ViewController
0x10000676c method ViewController      viewDidLoad
0x1000067d0 method ViewController      didReceiveMemoryWarning
0x1000067bc method ViewController c    thisIsAClassMethod
0x100006820 method ViewController c    andAnotherOne
'
run_test

NAME='objc method flags (icj)'
BROKEN=
FILE=../../bins/mach0/TestMethods
ARGS=
CMDS='icj~{[0].methods[2].flags[0]}
'
EXPECT='class
'
run_test

NAME='objc method flags (ic*)'
BROKEN=
FILE=../../bins/mach0/TestMethods
ARGS=
CMDS='ic*~thisIsAClassMethod
'
EXPECT='f method.class.ViewController.thisIsAClassMethod = 0x1000067bc
'
run_test
