#!/bin/sh
for a in . .. ../.. ../../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh; done

NAME='#81 into x86-32 only should return invalid on x86-64'
BROKEN=
FILE=malloc://1024
ARGS=
CMDS='e asm.arch=x86
e asm.bits=32
wx CE
e asm.bits = 64
pi 1'
EXPECT='invalid
'
run_test

NAME='16 bits - call 0'
BROKEN=
FILE=malloc://1024
ARGS=
CMDS='e asm.arch=x86
e asm.bits=16
wx e8fdff
pi 1'
EXPECT='call 0
'
run_test

NAME='16 bits longjump 1Mb'
BROKEN=
FILE=malloc://1024
ARGS=
CMDS='e asm.arch=x86
e asm.bits=16
s $s-16
wx 0f09e95bec
pi 2'
EXPECT='wbinvd
jmp 0xfec50
'
run_test

NAME='16 bits longjump 2Mb'
BROKEN=1
FILE=malloc://2048
ARGS=
CMDS='e asm.arch=x86
e asm.bits=16
s $s-16
wx 0f09e95bec
pi 2'
EXPECT='wbinvd
jmp 0x1eec50
'
run_test

