#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='MZ: corkami cdogs.exe - open'
FILE=../../bins/mz/cdogs.exe
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='MZ: corkami cdogs.exe - entrypoint'
FILE=../../bins/mz/cdogs.exe
CMDS='
s
'
EXPECT='0x41c
'
run_test

NAME='MZ: corkami cdogs.exe - pi 1'
FILE=../../bins/mz/cdogs.exe
CMDS='
pi 1
'
EXPECT='jmp 0x4c5
'
run_test

NAME='MZ: cdogs.exe segments'
FILE=../../bins/mz/cdogs.exe
CMDS='iS*'
EXPECT='fs sections
S 0x00000060 0x00000060 0x00002930 0x00002930 seg_000 23
f section.seg_000 10544 0x00000060
f section_end.seg_000 1 0x00002990
CC section 0 va=0x00000060 pa=0x00000060 sz=10544 vsz=10544 rwx=m-rwx seg_000 @ 0x00000060
S 0x00002990 0x00002990 0x00000402 0x00000402 seg_001 23
f section.seg_001 1026 0x00002990
f section_end.seg_001 1 0x00002d92
CC section 1 va=0x00002990 pa=0x00002990 sz=1026 vsz=1026 rwx=m-rwx seg_001 @ 0x00002990
'
run_test
