#!/bin/sh

# GPL 3+ - Copyright (C) 2013  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done
F=../../bins/java/ExCaseTableSwitch.class

NAME='java disasm crash'
IGNORE_ERR=1
BROKEN=
FILE=$F
ARGS=
CMDS='pd 10 >/dev/null
'
EXPECT=''
run_test

NAME='java switch crash'
IGNORE_ERR=1
BROKEN=
FILE=../../bins/fuzzed/zin7a5.class
ARGS=
CMDS='e scr.null=true
pd 100
'
EXPECT=''
run_test

NAME='java classes'
IGNORE_ERR=1
BROKEN=1
FILE=../../bins/java/DemoTest.class
ARGS=
CMDS='ic
'
EXPECT=''
run_test

NAME='java classes summary'
IGNORE_ERR=1
BROKEN=
FILE=../../bins/java/DemoTest.class
ARGS=
CMDS='java summary
'
EXPECT='Summary for ../../bins/java/DemoTest.class:
  Size 0x0:
  Constants  size: 0x166 count: 34:
  Methods    size: 0xb6 count: 4:
  Fields     size: 0x2 count: 0:
  Attributes size: 0xa count: 1:
  Interfaces size: 0x2 count: 0:
'
run_test
