#!/bin/sh

# GPL 3+ - Copyright (C) 2013  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done
F=../../bins/java/ExCaseTableSwitch.class

NAME='detect kotlin in java classes'
IGNORE_ERR=1
FILE=../../bins/java/HiKt.class
ARGS=
CMDS='i~lang[1]
'
EXPECT='kotlin
'
run_test


NAME='java disasm crash'
IGNORE_ERR=1
BROKEN=
FILE=$F
ARGS=
CMDS='pd 10 >/dev/null
'
EXPECT=''
run_test

NAME='java switch crash'
IGNORE_ERR=1
BROKEN=
FILE=../../bins/fuzzed/zin7a5.class
ARGS=
CMDS='e scr.null=true
pd 100
'
EXPECT=''
run_test

NAME='java classes'
IGNORE_ERR=1
BROKEN=
FILE=../../bins/java/DemoTest.class
ARGS=
CMDS='ic
'
EXPECT='0x00000000 [0x00000190 - 0x00000211] (sz 129) class 0 DemoTest super: java/lang/Object
0x00000190 method 0      fun
0x000001b9 method 1      <init>
0x000001e8 method 2      res
0x00000211 method 3      main
'
run_test

NAME='java classes summary'
IGNORE_ERR=1
BROKEN=
FILE=../../bins/java/DemoTest.class
ARGS=
CMDS='java summary
'
EXPECT='Summary for ../../bins/java/DemoTest.class:
  Size 0x0:
  Constants  size: 0x166 count: 34:
  Methods    size: 0xb6 count: 4:
  Fields     size: 0x2 count: 0:
  Attributes size: 0xa count: 1:
  Interfaces size: 0x2 count: 0:
'
run_test
