#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='ELF: corkami elf-relro - sections'
FILE=../../bins/elf/analysis/elf-relro
ARGS=''
CMDS="S~rel"
EXPECT='[08] . 0x0000027c -r-- va=0x0804827c sz=0x0008 vsz=0x0008 .rel.dyn
[09] . 0x00000284 -r-- va=0x08048284 sz=0x0010 vsz=0x0010 .rel.plt
'
run_test

NAME='ELF: corkami elf-relro - relro enabled'
FILE=../../bins/elf/analysis/elf-relro
ARGS=''
CMDS="ik~relro"

EXPECT='elf.relro=partial relro
'
run_test


NAME='ELF: imports partial relro'
FILE=../../bins/elf/vim
ARGS=''
CMDS="ik~relro
ii"

EXPECT='elf.relro=partial relro
[Imports]
ordinal=002 plt=0x00051f60 bind=GLOBAL type=FUNC name=__ctype_toupper_loc
ordinal=003 plt=0x00051f68 bind=GLOBAL type=FUNC name=__strcat_chk
ordinal=004 plt=0x00051f70 bind=GLOBAL type=FUNC name=getenv
ordinal=005 plt=0x00051f78 bind=GLOBAL type=FUNC name=utime
ordinal=006 plt=0x00051f80 bind=GLOBAL type=FUNC name=sigprocmask
ordinal=007 plt=0x00051f88 bind=GLOBAL type=FUNC name=free
ordinal=008 plt=0x00051f90 bind=GLOBAL type=FUNC name=putchar
ordinal=009 plt=0x00051f98 bind=GLOBAL type=FUNC name=is_selinux_enabled
ordinal=010 plt=0x00051fa0 bind=GLOBAL type=FUNC name=strcasecmp
ordinal=011 plt=0x00051fa8 bind=GLOBAL type=FUNC name=Gpm_Open
ordinal=012 plt=0x00051fb0 bind=GLOBAL type=FUNC name=localtime
ordinal=013 plt=0x00051fb8 bind=GLOBAL type=FUNC name=mblen
ordinal=014 plt=0x00051fc0 bind=GLOBAL type=FUNC name=__errno_location
ordinal=015 plt=0x00051fc8 bind=GLOBAL type=FUNC name=unlink
ordinal=016 plt=0x00051fd0 bind=GLOBAL type=FUNC name=strncpy
ordinal=017 plt=0x00051fd8 bind=GLOBAL type=FUNC name=strncmp
ordinal=018 plt=0x00443a32 bind=WEAK type=NOTYPE name=_ITM_deregisterTMCloneTable
ordinal=019 plt=0x00051fe0 bind=GLOBAL type=FUNC name=_exit
ordinal=020 plt=0x00051fe8 bind=GLOBAL type=FUNC name=strcpy
ordinal=021 plt=0x00051ff0 bind=GLOBAL type=FUNC name=mkdir
ordinal=022 plt=0x00051ff8 bind=GLOBAL type=FUNC name=tputs
ordinal=023 plt=0x00052000 bind=GLOBAL type=FUNC name=iconv
ordinal=024 plt=0x00052008 bind=GLOBAL type=FUNC name=ferror
ordinal=025 plt=0x00052010 bind=GLOBAL type=FUNC name=qsort
ordinal=026 plt=0x00052018 bind=GLOBAL type=FUNC name=isatty
ordinal=027 plt=0x00052020 bind=GLOBAL type=FUNC name=sigaction
ordinal=028 plt=0x00052028 bind=GLOBAL type=FUNC name=fread
ordinal=029 plt=0x00052030 bind=GLOBAL type=FUNC name=strtod
ordinal=030 plt=0x00052038 bind=GLOBAL type=FUNC name=exp
ordinal=031 plt=0x00052040 bind=GLOBAL type=FUNC name=readlink
ordinal=032 plt=0x00052048 bind=GLOBAL type=FUNC name=fcntl
ordinal=033 plt=0x00052050 bind=GLOBAL type=FUNC name=setenv
ordinal=034 plt=0x00052058 bind=GLOBAL type=FUNC name=write
ordinal=035 plt=0x00052060 bind=GLOBAL type=FUNC name=getpid
ordinal=036 plt=0x00052068 bind=GLOBAL type=FUNC name=textdomain
ordinal=037 plt=0x00052070 bind=GLOBAL type=FUNC name=atan
ordinal=038 plt=0x00052078 bind=GLOBAL type=FUNC name=tgoto
ordinal=039 plt=0x00052080 bind=GLOBAL type=FUNC name=fclose
ordinal=040 plt=0x00052088 bind=GLOBAL type=FUNC name=__xstat64
ordinal=041 plt=0x00052090 bind=GLOBAL type=FUNC name=opendir
ordinal=042 plt=0x00052098 bind=GLOBAL type=FUNC name=getpwuid
ordinal=043 plt=0x000520a0 bind=GLOBAL type=FUNC name=ctime
ordinal=044 plt=0x000520a8 bind=GLOBAL type=FUNC name=bindtextdomain
ordinal=045 plt=0x000520b0 bind=GLOBAL type=FUNC name=stpcpy
ordinal=046 plt=0x000520b8 bind=GLOBAL type=FUNC name=rmdir
ordinal=047 plt=0x000520c0 bind=GLOBAL type=FUNC name=dcgettext
ordinal=048 plt=0x000520c8 bind=GLOBAL type=FUNC name=strlen
ordinal=049 plt=0x000520d0 bind=GLOBAL type=FUNC name=chdir
ordinal=050 plt=0x000520d8 bind=GLOBAL type=FUNC name=__stack_chk_fail
ordinal=051 plt=0x000520e0 bind=GLOBAL type=FUNC name=getuid
ordinal=052 plt=0x000520e8 bind=GLOBAL type=FUNC name=dup2
ordinal=053 plt=0x000520f0 bind=GLOBAL type=FUNC name=tcflush
ordinal=054 plt=0x000520f8 bind=GLOBAL type=FUNC name=strchr
ordinal=055 plt=0x00052100 bind=GLOBAL type=FUNC name=printf
ordinal=056 plt=0x00052108 bind=GLOBAL type=FUNC name=rewind
ordinal=057 plt=0x00052110 bind=GLOBAL type=FUNC name=_IO_putc
ordinal=058 plt=0x00052118 bind=GLOBAL type=FUNC name=__fdelt_chk
ordinal=059 plt=0x00052120 bind=GLOBAL type=FUNC name=nanosleep
ordinal=060 plt=0x00052128 bind=GLOBAL type=FUNC name=strrchr
ordinal=061 plt=0x00052130 bind=GLOBAL type=FUNC name=uname
ordinal=062 plt=0x00052138 bind=GLOBAL type=FUNC name=dup
ordinal=063 plt=0x00052140 bind=GLOBAL type=FUNC name=gettimeofday
ordinal=064 plt=0x00052148 bind=GLOBAL type=FUNC name=__assert_fail
ordinal=065 plt=0x00052150 bind=GLOBAL type=FUNC name=fputs
ordinal=066 plt=0x00052158 bind=GLOBAL type=FUNC name=memset
ordinal=067 plt=0x00052160 bind=GLOBAL type=FUNC name=tgetflag
ordinal=068 plt=0x00052168 bind=GLOBAL type=FUNC name=pow
ordinal=069 plt=0x00052170 bind=GLOBAL type=FUNC name=ioctl
ordinal=070 plt=0x00052178 bind=GLOBAL type=FUNC name=getcwd
ordinal=071 plt=0x00052180 bind=GLOBAL type=FUNC name=log
ordinal=072 plt=0x00052188 bind=GLOBAL type=FUNC name=strncat
ordinal=073 plt=0x00052190 bind=GLOBAL type=FUNC name=alarm
ordinal=074 plt=0x00052198 bind=GLOBAL type=FUNC name=close
ordinal=075 plt=0x000521a0 bind=GLOBAL type=FUNC name=tgetent
ordinal=076 plt=0x000521a8 bind=GLOBAL type=FUNC name=pipe
ordinal=077 plt=0x000521b0 bind=GLOBAL type=FUNC name=setsid
ordinal=078 plt=0x000521b8 bind=GLOBAL type=FUNC name=fmod
ordinal=079 plt=0x000521c0 bind=GLOBAL type=FUNC name=closedir
ordinal=080 plt=0x000521c8 bind=GLOBAL type=FUNC name=cos
ordinal=081 plt=0x000521d0 bind=GLOBAL type=FUNC name=fputc
ordinal=082 plt=0x000521d8 bind=GLOBAL type=FUNC name=memchr
ordinal=083 plt=0x000521e0 bind=GLOBAL type=FUNC name=ftello64
ordinal=084 plt=0x000521e8 bind=GLOBAL type=FUNC name=acos
ordinal=085 plt=0x000521f0 bind=GLOBAL type=FUNC name=read
ordinal=086 plt=0x00443a32 bind=GLOBAL type=FUNC name=__libc_start_main
ordinal=087 plt=0x000521f8 bind=GLOBAL type=FUNC name=srand
ordinal=088 plt=0x00052200 bind=GLOBAL type=FUNC name=memcmp
ordinal=089 plt=0x00052208 bind=GLOBAL type=FUNC name=fgets
ordinal=090 plt=0x00052210 bind=GLOBAL type=FUNC name=tgetnum
ordinal=091 plt=0x00052218 bind=GLOBAL type=FUNC name=getsockopt
ordinal=092 plt=0x00052220 bind=GLOBAL type=FUNC name=_setjmp
ordinal=093 plt=0x00052228 bind=GLOBAL type=FUNC name=acl_set_file
ordinal=094 plt=0x00052230 bind=GLOBAL type=FUNC name=__fxstat64
ordinal=095 plt=0x00052238 bind=GLOBAL type=FUNC name=strcmp
ordinal=096 plt=0x00052240 bind=GLOBAL type=FUNC name=signal
ordinal=097 plt=0x00052248 bind=GLOBAL type=FUNC name=getpwnam
ordinal=098 plt=0x00052250 bind=GLOBAL type=FUNC name=gethostbyname
ordinal=099 plt=0x00052258 bind=GLOBAL type=FUNC name=log10
ordinal=100 plt=0x00052260 bind=GLOBAL type=FUNC name=__memmove_chk
ordinal=101 plt=0x00052268 bind=GLOBAL type=FUNC name=setpwent
ordinal=102 plt=0x00052270 bind=GLOBAL type=FUNC name=__memcpy_chk
ordinal=103 plt=0x00052278 bind=GLOBAL type=FUNC name=fprintf
ordinal=104 plt=0x00052280 bind=GLOBAL type=FUNC name=sigemptyset
ordinal=105 plt=0x00052288 bind=GLOBAL type=FUNC name=ftell
ordinal=106 plt=0x00052290 bind=GLOBAL type=FUNC name=feof
ordinal=107 plt=0x00443a32 bind=WEAK type=NOTYPE name=__gmon_start__
ordinal=108 plt=0x00052298 bind=GLOBAL type=FUNC name=umask
ordinal=109 plt=0x000522a0 bind=GLOBAL type=FUNC name=fopen64
ordinal=110 plt=0x000522a8 bind=GLOBAL type=FUNC name=strtol
ordinal=111 plt=0x000522b0 bind=GLOBAL type=FUNC name=memcpy
ordinal=112 plt=0x000522b8 bind=GLOBAL type=FUNC name=getfilecon
ordinal=113 plt=0x000522c0 bind=GLOBAL type=FUNC name=getpwent
ordinal=114 plt=0x000522c8 bind=GLOBAL type=FUNC name=cosh
ordinal=115 plt=0x000522d0 bind=GLOBAL type=FUNC name=kill
ordinal=116 plt=0x000522d8 bind=GLOBAL type=FUNC name=time
ordinal=117 plt=0x000522e0 bind=GLOBAL type=FUNC name=fileno
ordinal=118 plt=0x000522e8 bind=GLOBAL type=FUNC name=__stpcpy_chk
ordinal=119 plt=0x000522f0 bind=GLOBAL type=FUNC name=getgid
ordinal=120 plt=0x000522f8 bind=GLOBAL type=FUNC name=iswupper
ordinal=121 plt=0x00052300 bind=GLOBAL type=FUNC name=select
ordinal=122 plt=0x00052308 bind=GLOBAL type=FUNC name=getrlimit64
ordinal=123 plt=0x00052310 bind=GLOBAL type=FUNC name=dlopen
ordinal=124 plt=0x00052318 bind=GLOBAL type=FUNC name=sync
ordinal=125 plt=0x00052320 bind=GLOBAL type=FUNC name=sinh
ordinal=126 plt=0x00052328 bind=GLOBAL type=FUNC name=pthread_getspecific
ordinal=127 plt=0x00052330 bind=GLOBAL type=FUNC name=malloc
ordinal=128 plt=0x00052338 bind=GLOBAL type=FUNC name=strncasecmp
ordinal=129 plt=0x00052340 bind=GLOBAL type=FUNC name=fflush
ordinal=130 plt=0x00052348 bind=GLOBAL type=FUNC name=_IO_getc
ordinal=131 plt=0x00052350 bind=GLOBAL type=FUNC name=acl_get_file
ordinal=132 plt=0x00052358 bind=GLOBAL type=FUNC name=nl_langinfo
ordinal=133 plt=0x00052360 bind=GLOBAL type=FUNC name=tan
ordinal=134 plt=0x00052368 bind=GLOBAL type=FUNC name=ungetc
ordinal=135 plt=0x00052370 bind=GLOBAL type=FUNC name=endpwent
ordinal=136 plt=0x00052378 bind=GLOBAL type=FUNC name=sscanf
ordinal=137 plt=0x00052380 bind=GLOBAL type=FUNC name=atan2
ordinal=138 plt=0x00052388 bind=GLOBAL type=FUNC name=strpbrk
ordinal=139 plt=0x00052390 bind=GLOBAL type=FUNC name=fseek
ordinal=140 plt=0x00052398 bind=GLOBAL type=FUNC name=fseeko64
ordinal=141 plt=0x000523a0 bind=GLOBAL type=FUNC name=bind_textdomain_codeset
ordinal=142 plt=0x000523a8 bind=GLOBAL type=FUNC name=fchdir
ordinal=143 plt=0x000523b0 bind=GLOBAL type=FUNC name=dlclose
ordinal=144 plt=0x000523b8 bind=GLOBAL type=FUNC name=setfilecon
ordinal=145 plt=0x000523c0 bind=GLOBAL type=FUNC name=realloc
ordinal=146 plt=0x000523c8 bind=GLOBAL type=FUNC name=__strcpy_chk
ordinal=147 plt=0x000523d0 bind=GLOBAL type=FUNC name=fdopen
ordinal=148 plt=0x000523d8 bind=GLOBAL type=FUNC name=mkdtemp
ordinal=149 plt=0x000523e0 bind=GLOBAL type=FUNC name=setlocale
ordinal=150 plt=0x000523e8 bind=GLOBAL type=FUNC name=iconv_close
ordinal=151 plt=0x000523f0 bind=GLOBAL type=FUNC name=chmod
ordinal=152 plt=0x000523f8 bind=GLOBAL type=FUNC name=sigset
ordinal=153 plt=0x00052400 bind=GLOBAL type=FUNC name=__longjmp_chk
ordinal=154 plt=0x00052408 bind=GLOBAL type=FUNC name=open64
ordinal=155 plt=0x00052410 bind=GLOBAL type=FUNC name=strftime
ordinal=156 plt=0x00052418 bind=GLOBAL type=FUNC name=memmove
ordinal=157 plt=0x00052420 bind=GLOBAL type=FUNC name=readdir64
ordinal=158 plt=0x00052428 bind=GLOBAL type=FUNC name=fsync
ordinal=159 plt=0x00052430 bind=GLOBAL type=FUNC name=Gpm_GetEvent
ordinal=160 plt=0x00052438 bind=GLOBAL type=FUNC name=waitpid
ordinal=161 plt=0x00052440 bind=GLOBAL type=FUNC name=tcgetattr
ordinal=162 plt=0x00052448 bind=GLOBAL type=FUNC name=tcsetattr
ordinal=163 plt=0x00052450 bind=GLOBAL type=FUNC name=access
ordinal=164 plt=0x00052458 bind=GLOBAL type=FUNC name=fchown
ordinal=165 plt=0x00052460 bind=GLOBAL type=FUNC name=dcngettext
ordinal=166 plt=0x00052468 bind=GLOBAL type=FUNC name=perror
ordinal=167 plt=0x00052470 bind=GLOBAL type=FUNC name=strtok
ordinal=168 plt=0x00052478 bind=GLOBAL type=FUNC name=sysconf
ordinal=169 plt=0x00443a32 bind=WEAK type=NOTYPE name=_Jv_RegisterClasses
ordinal=170 plt=0x00052480 bind=GLOBAL type=FUNC name=towlower
ordinal=171 plt=0x00052488 bind=GLOBAL type=FUNC name=rename
ordinal=172 plt=0x00052490 bind=GLOBAL type=FUNC name=tgetstr
ordinal=173 plt=0x00052498 bind=GLOBAL type=FUNC name=towupper
ordinal=174 plt=0x000524a0 bind=GLOBAL type=FUNC name=sin
ordinal=175 plt=0x000524a8 bind=GLOBAL type=FUNC name=floor
ordinal=176 plt=0x000524b0 bind=GLOBAL type=FUNC name=execvp
ordinal=177 plt=0x000524b8 bind=GLOBAL type=FUNC name=getpgid
ordinal=178 plt=0x000524c0 bind=GLOBAL type=FUNC name=__lxstat64
ordinal=179 plt=0x000524c8 bind=GLOBAL type=FUNC name=sysinfo
ordinal=180 plt=0x000524d0 bind=GLOBAL type=FUNC name=strcat
ordinal=181 plt=0x000524d8 bind=GLOBAL type=FUNC name=freecon
ordinal=182 plt=0x000524e0 bind=GLOBAL type=FUNC name=tanh
ordinal=183 plt=0x000524e8 bind=GLOBAL type=FUNC name=asin
ordinal=184 plt=0x000524f0 bind=GLOBAL type=FUNC name=__memset_chk
ordinal=185 plt=0x000524f8 bind=GLOBAL type=FUNC name=sprintf
ordinal=186 plt=0x00052500 bind=GLOBAL type=FUNC name=exit
ordinal=187 plt=0x00052508 bind=GLOBAL type=FUNC name=connect
ordinal=188 plt=0x00052510 bind=GLOBAL type=FUNC name=fwrite
ordinal=189 plt=0x00052518 bind=GLOBAL type=FUNC name=lseek64
ordinal=190 plt=0x00052520 bind=GLOBAL type=FUNC name=__fprintf_chk
ordinal=191 plt=0x00443a32 bind=WEAK type=NOTYPE name=_ITM_registerTMCloneTable
ordinal=192 plt=0x00052528 bind=GLOBAL type=FUNC name=sqrt
ordinal=193 plt=0x00052530 bind=GLOBAL type=FUNC name=sigaltstack
ordinal=194 plt=0x00052538 bind=GLOBAL type=FUNC name=strerror
ordinal=195 plt=0x00052540 bind=GLOBAL type=FUNC name=execl
ordinal=196 plt=0x00052548 bind=GLOBAL type=FUNC name=dlsym
ordinal=197 plt=0x00052550 bind=GLOBAL type=FUNC name=ceil
ordinal=198 plt=0x00052558 bind=GLOBAL type=FUNC name=sleep
ordinal=199 plt=0x00052560 bind=GLOBAL type=FUNC name=Gpm_Close
ordinal=200 plt=0x00052568 bind=WEAK type=FUNC name=__cxa_finalize
ordinal=201 plt=0x00052570 bind=GLOBAL type=FUNC name=sigaddset
ordinal=202 plt=0x00052578 bind=GLOBAL type=FUNC name=fork
ordinal=203 plt=0x00052580 bind=GLOBAL type=FUNC name=strstr
ordinal=204 plt=0x00052588 bind=GLOBAL type=FUNC name=rand
ordinal=205 plt=0x00052590 bind=GLOBAL type=FUNC name=dlerror
ordinal=206 plt=0x00052598 bind=GLOBAL type=FUNC name=__ctype_tolower_loc
ordinal=207 plt=0x000525a0 bind=GLOBAL type=FUNC name=__ctype_b_loc
ordinal=208 plt=0x000525a8 bind=GLOBAL type=FUNC name=acl_free
ordinal=209 plt=0x000525b0 bind=GLOBAL type=FUNC name=iconv_open
ordinal=210 plt=0x000525b8 bind=GLOBAL type=FUNC name=__sprintf_chk
ordinal=211 plt=0x000525c0 bind=GLOBAL type=FUNC name=socket

210 imports
'
run_test
