#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='ELF: PHDR Linux reload trick'
FILE=../../bins/elf/textile_hitcon2017
CMDS="pi 1 @ 0x4011FA
"

EXPECT='call sym.imp.strcmp_1
'
run_test
