#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh && break ; done

FILE=../../bins/elf/analysis/x86-helloworld-phdr
IGNORE_ERR=1
CMDS='
S
'
EXPECT='[00:00] * pa=0x00000000 mr-x va=0x08048000 sz=0x0100 vsz=0x0100 LOAD0
[00:01] . pa=0x00000130 mrwx va=0x08049130 sz=0x0100 vsz=0x0100 LOAD1
'

run_test
