#!/bin/sh

# GPL 3+ - Copyright (C) 2016 - pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='dbg.di'
FILE=/bin/ls
ARGS=-d
BROKEN=
IGNORE_ERR=1
CMDS='
di~baddr
'
EXPECT='baddr=0x100000000
'
run_test

