#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

FILE=../../bins/mach0/ls-osx-x86_64
CMDS='e anal.noncode=false
afr
afl~?str.

'
EXPECT='0
'
run_test

FILE=../../bins/mach0/ls-osx-x86_64
CMDS='e anal.noncode=false
e anal.calls=true
af
afl~?str.

'
EXPECT='0
'
run_test
