#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

FILE=../../bins/pe/standard.exe
CMDS='aaa
afi @ sub.msvcrt.dll_printf_b2d~name

'
EXPECT='name: sub.msvcrt.dll_printf_b2d
'
run_test

FILE=../../bins/pe/ioli/w32/crackme0x00.exe
BROKEN=1
CMDS='aaa
pd 1 @ sym.imp.msvcrt.dll_strlen~?dword

'
EXPECT='1
'
run_test

FILE=../../bins/pe/testx64.exe
BROKEN=1
CMDS='aaa
pd 1 @ sym.imp.VCRUNTIME140.dll_memset~?qword

'
EXPECT='1
'
run_test
