#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

unset R2_NOPLUGINS

F0=../../bins/pcap/sample0.pcap

NAME="pcap info"
FILE=$F0
ARGS=
CMDS="i"
EXPECT="blksz    0x0
block    0x100
fd       6
file     ../../bins/pcap/sample0.pcap
format   pcap
iorw     false
mode     -r--
size     0xd4b64
humansz  850.8K
type     tcpdump capture file - version 2.4 (Ethernet, capture length 262144)
"
run_test

NAME="pcap file header"
FILE=$F0
ARGS=
CMDS="pd 1"
EXPECT="            ;-- tcpdump capture file - version 2.4 (Ethernet, capture length 262144):
            0x00000000      d4             invalid
"
run_test

NAME="pcap frame header"
FILE=$F0
ARGS=
CMDS="
s 0x18
pd 1
"
EXPECT="            ;-- 0x18: Frame 1, 74 bytes on wire, 74 bytes captured:
            0x00000018      3e87ce         xchg esi, ecx
"
run_test

NAME="pcap ethernet header"
FILE=$F0
ARGS=
CMDS="
s 0x28
pd 1
"
EXPECT="            ;-- 0x28: Ethernet, Src: 00:00:00:00:00:00, Dst: 00:00:00:00:00:00:
            0x00000028      0000           add byte [rax], al
"
run_test

NAME="pcap ipv4 header"
FILE=$F0
ARGS=
CMDS="
s 0x36
pd 1
"
EXPECT="            ;-- 0x36: IPV4, Src: 127.0.0.1, Dst: 127.0.0.1:
            0x00000036      450000         add byte [r8], r8b
"
run_test

NAME="pcap tcp header"
FILE=$F0
ARGS=
CMDS="
s 0x4a
pd 1
"
EXPECT="            ;-- 0x4a: Transmission Control Protocol, Src Port: 58728, Dst port: 8888, Len: 0:
            0x0000004a      e568           in eax, 0x68                ; 'h'
"
run_test

NAME="pcap tcp string data"
FILE=$F0
ARGS=
CMDS="
s 0x3f3
pd 2
"
EXPECT='            0x000003f3  ~   d09824715375   rcr byte [rax + 0x75537124], 1
            ;-- str._qSupported:multiprocess__swbreak__hwbreak__qRelocInsn__fork_events__vfork_events__exec_events__vContSupported__QThreadEvents__no_resumed__xmlRegisters_i386_6a:
            0x000003f5     .string "$qSupported:multiprocess+;swbreak+;hwbreak+;qRelocInsn+;fork-events+;vfork-events+;exec-events+;vContSupported+;QThreadEvents+;no-resumed+;xmlRegisters=i386#6a" ; len=160
'
run_test
