#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

BROKEN=
NAME="320c64 OPEX"
FILE=malloc://512280
CMDS='e asm.arch=tms320
e asm.cpu=c64x
wx 0041bd10
aoj~{}
'
EXPECT='[
  {
    "opcode": "b 0x20de8",
    "disasm": "b 0x20de8",
    "mnemonic": "b",
    "prefix": 0,
    "id": 17,
    "opex": {
      "operands": [
        {
          "type": "imm",
          "value": 134632
        }
      ]
    },
    "addr": 0,
    "bytes": "0041bd10",
    "size": 4,
    "type": "jmp",
    "jump": 134632,
    "refptr": 0,
    "cycles": 0,
    "delay": 0,
    "family": "cpu"
  }
]
'
run_test
