#!/bin/bash

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="call [esp]"
FILE=../bins/pe/Lab01-03.exe

CMDS='
e io.cache = true
aei
aeim
aeip
aecu 0x00405026
px 4 @ esp
aes
aer~eip
'
EXPECT='- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00177ff8  1550 4000                                .P@.
eip = 0x00405015
'

run_test
