#!/bin/bash

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="call [esp]"
FILE=../bins/pe/Lab01-03.exe
BROKEN=1

CMDS='
e io.cache = true
aei
aeim
aeip
aecu 0x00405026
p8 4 @ esp
aes
aer~eip
'
EXPECT='15504000
eip = 0x00405015
'

run_test
