#!/bin/sh

# GPL 3+ - Copyright (C) 2015  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='dh esil'
FILE=-
ARGS='-a x86 -b 32'
CMDS='
aei
aeim
aeip
dr esp=0x00108000
.dr*
"wa mov eax, 0x1234;push eax"
ds 2
.dr*
dr?esp
?v [esp]
'
EXPECT='0x00107ffc
0x1234
'
run_test
NAME='aek-'
FILE=-
ARGS=
CMDS='
e esil.stats = true
wx 41574156415541544989f4555389fd4881eca8030000488b3e64488b042528
aei
aeim
aeip
aes
aek *~?mem.write
aek-
aek *~?
'
EXPECT='1
0
'
run_test

NAME='aek- - crash'
FILE='-'
CMDS='aek-'
run_test
