#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='elf swift'
FILE=../../bins/elf/analysis/hello-swift
BROKEN=
ARGS=
CMDS='i~lang[1]'
EXPECT='swift
'
run_test

NAME='elf swift demangle (requires swift-demangle program)'
FILE=../../bins/elf/analysis/hello-swift
ARGS=
CMDS='isq~0x004009e0'
EXPECT='0x004009e0 16 Swift.String.init (_builtinStringLiteral(Builtin.RawPointer byteSize__Builtin.Word isASCII__Builtin.Int1 _) -> String
'
run_test

