#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done


NAME='iS. and iSj. implementation'
FILE=../../bins/anal/lab1B
CMDS='s 0x188
iS.
s 0x08058000
iS.
s 0x760
iSj.
'
EXPECT='Current section
00 0x00000188    36 0x08048188    36 --r-- .note.gnu.build_id
Current section
{"name":".plt","size":240,"vsize":240,"flags":"--r-x","paddr":1888,"vaddr":134514528}'
run_test

NAME='iE and iE. implementation'
FILE=../../bins/anal/lab1B
CMDS='s 0x080489b9
iE.
s 0x080489a6
s+5
isj.
'
EXPECT='Current export
022 0x000009b7 0x080489b7 GLOBAL   FUNC  189 decrypt
{"name":"prog_timeout","demname":"","flagname":"sym.prog_timeout","ordinal":35,"bind":"GLOBAL","size":17,"type":"FUNC","vaddr":134515110,"paddr":2470}'
run_test
