#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done


NAME='WASM: Wasm - open'
BROKEN=
FILE=../../bins/wasm/basic.wasm
IGNORE_ERR=1
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='WASM: Wasm - detection'
BROKEN=
FILE=../../bins/wasm/basic.wasm
IGNORE_ERR=1
ARGS=''
CMDS="iI~os"
EXPECT='os       Wasm
'
run_test

NAME='WASM: Wasm - entrypoint'
BROKEN=
FILE=../../bins/wasm/start.wasm
IGNORE_ERR=1
ARGS=''
CMDS="ie~vaddr"
EXPECT='vaddr=0x0000002d paddr=0x0000002d baddr=0x00000000 laddr=0x00000000 haddr=-1 type=program
'
run_test

NAME='WASM: Wasm - sections'
BROKEN=
FILE=../../bins/wasm/binary.wasm
IGNORE_ERR=1
ARGS=''
CMDS="iS"
EXPECT='[Sections]
00 0x0000000a    16 0x0000000a    16 ----- type
01 0x0000001d    44 0x0000001d    44 ----- function
02 0x0000004d   476 0x0000004d   476 ----- export
03 0x0000022d   502 0x0000022d   502 ----- code
'
run_test
