#!/bin/sh
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='T hello'
CMDS='
T hello
T
'
EXPECT="1 hello
"
run_test

NAME='T-*'
CMDS='
T hello
T-*
T
'
EXPECT=''
run_test

NAME='T hello world'
CMDS='
T hello
T world
T
'
EXPECT='1 hello
2 world
'
run_test

NAME='T-1'
CMDS='
T hello
T world
T-1
T
'
EXPECT='2 world
'
run_test

NAME='T-2'
CMDS='
T hello
T world
T-2
T
'
EXPECT=''
run_test

NAME='T-3'
CMDS='
T hello
T world
T-3
T
'
EXPECT=''
run_test
