#!/bin/sh
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='Cvb variable null pointer deref'
FILE=../bins/elf/analysis/x64-simple
CMDS='
aaa
Cvb local_10'
EXPECT=''
run_test

NAME='CC.'
FILE=-
CMDS='CC hello @ 10
CC.
CC.10
CC.@10
CC@10
'
EXPECT='hello
hello
0x0000000a CCu "hello"
'
run_test
