#!/bin/sh
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='att relsub'
FILE=../bins/mach0/mac-ls
CMDS='e asm.syntax=att
e asm.lines=0
e asm.bytes=0
e asm.comments=false
pd 20
'
EXPECT='  ;-- main:
  ;-- entry0:
  ;-- func.100001058:
 0x100001058      pushq %rbp
 0x100001059      movq %rsp, %rbp
 0x10000105c      pushq %r15
 0x10000105e      pushq %r14
 0x100001060      pushq %r13
 0x100001062      pushq %r12
 0x100001064      pushq %rbx
 0x100001065      subq $0x648, %rsp
 0x10000106c      movq %rsi, %rbx
 0x10000106f      movl %edi, %r14d
 0x100001072      leaq -0x640(%rbp), %rax
 0x100001079      movq %rax, -0x648(%rbp)
 0x100001080      testl %r14d, %r14d
 0x100001083      jg 0x10000108a
 0x100001085      callq sym.func.100004401
 0x10000108a      leaq 0x100004b10, %rsi
 0x100001091      xorl %edi, %edi
 0x100001093      callq sym.imp.setlocale
 0x100001098      movl $1, %r13d
 0x10000109e      movl $1, %edi
'
run_test

NAME='att varsub'
FILE=../bins/mach0/mac-ls
CMDS='af
e asm.syntax=att
e asm.vars=0
e asm.lines=0
e asm.bytes=0
e asm.comments=false
pd 20
'
EXPECT='  ;-- entry0:
  ;-- func.100001058:
/ (fcn) main 1277
| 0x100001058      pushq %rbp
| 0x100001059      movq %rsp, %rbp
| 0x10000105c      pushq %r15
| 0x10000105e      pushq %r14
| 0x100001060      pushq %r13
| 0x100001062      pushq %r12
| 0x100001064      pushq %rbx
| 0x100001065      subq $0x648, %rsp
| 0x10000106c      movq %rsi, %rbx
| 0x10000106f      movl %edi, %r14d
| 0x100001072      leaq local_640h, %rax
| 0x100001079      movq %rax, local_648h
| 0x100001080      testl %r14d, %r14d
| 0x100001083      jg 0x10000108a
| 0x100001085      callq sym.func.100004401
| 0x10000108a      leaq 0x100004b10, %rsi
| 0x100001091      xorl %edi, %edi
| 0x100001093      callq sym.imp.setlocale
| 0x100001098      movl $1, %r13d
| 0x10000109e      movl $1, %edi
'
run_test

NAME='att varsub 2'
FILE=../bins/elf/varsub
CMDS='aa; s main
e asm.syntax=att
e asm.vars=0
e asm.lines=0
e asm.bytes=0
e asm.comments=false
pdf
'
EXPECT='  ;-- main:
/ (fcn) main 42
| 0x004004a6      pushq %rbp
| 0x004004a7      movq %rsp, %rbp
| 0x004004aa      movq arg_8h, %rax
| 0x004004af      movq -8(%rsp), %rax
| 0x004004b4      movq arg_8h_2, %rax
| 0x004004b8      movq local_8h, %rax
| 0x004004bc      movq arg_16h, %rax
| 0x004004c1      movq -0x16(%rsp), %rax
| 0x004004c6      movq arg_16h_2, %rax
| 0x004004ca      movq local_16h, %rax
| 0x004004ce      leave
\ 0x004004cf      retq
'
run_test

NAME='att varsub 2 with asm.varsub_only disabled'
FILE=../bins/elf/varsub
CMDS='aa; s main
e asm.syntax=att
e asm.vars=0
e asm.lines=0
e asm.bytes=0
e asm.comments=false
e asm.varsub_only=false
pdf
'
EXPECT='  ;-- main:
/ (fcn) main 42
| 0x004004a6      pushq %rbp
| 0x004004a7      movq %rsp, %rbp
| 0x004004aa      movq arg_8h(%rsp), %rax
| 0x004004af      movq -8(%rsp), %rax
| 0x004004b4      movq arg_8h_2(%rbp), %rax
| 0x004004b8      movq local_8h(%rbp), %rax
| 0x004004bc      movq arg_16h(%rsp), %rax
| 0x004004c1      movq -0x16(%rsp), %rax
| 0x004004c6      movq arg_16h_2(%rbp), %rax
| 0x004004ca      movq local_16h(%rbp), %rax
| 0x004004ce      leave
\ 0x004004cf      retq
'
run_test
