#!/bin/sh
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='no flags'
CMDS='f patata
f-*
f~?
'
EXPECT='0
'
run_test

NAME='no flags'
FILE=../bins/elf/analysis/elf-relro
BROKEN=
CMDS='f patata
fs *
f-*
f~?
'
EXPECT='0
'
run_test

NAME='fr foo bar'
FILE=-
BROKEN=
CMDS='f foo
fr foo bar
f
pd 1
'
EXPECT='0x00000000 1 bar
            ;-- bar:
            0x00000000      0000           add byte [rax], al
'
run_test
