#!/bin/sh
# GPL 3+ - Copyright (C) 2017  pancake
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='cmd.hit sugar for /x'
FILE='malloc://1024'
CMDS='
wx 90 @ 10
e cmd.hit=wx 91
/x 90
p8 1 @ 10
'
EXPECT='0x0000000a hit0_0 90
91
'
run_test

NAME='cmd.hit sugar for /j'
FILE='malloc://1024'
CMDS='w hello @ 10
psz @@/j hello
'
EXPECT='[{"offset":10,"type":"string","data":"hello"}hello
]
'
run_test

NAME='/xj utf16'
FILE='malloc://1024'
CMDS='wx 005c
/xj 005c
'
EXPECT='[{"offset":0,"type":"hexpair","data":"005c"}]
'
run_test

NAME='/j utf16'
FILE='malloc://1024'
CMDS='wx 005c
/j \x00\\
'
EXPECT='[{"offset":0,"type":"string","data":"\u0000\\"}]
'
run_test

NAME='cmd.hit sugar for /x'
FILE='malloc://1024'
CMDS='wx 90 @ 10
wx 91 @@/x 90
p8 1 @ 10
'
EXPECT='0x0000000a hit0_0 90
91
'
run_test

NAME='cmd.hit sugar for /'
FILE='malloc://1024'
CMDS='w A @ 10
wx 33 @@/ A
p8 1 @ 10
'
EXPECT='0x0000000a hit0_0 "A"
33
'
run_test

NAME='cmd.hit sugar for /'
FILE='malloc://1024'
CMDS='wx 90 @ 10
wx 33 @@/c nop
p8 1 @ 10
'
EXPECT='0x0000000a   # 1: nop
33
'
run_test

NAME='cmd.hit for /!x'
BROKEN=
FILE='malloc://1024'
CMDS='e cmd.hit = p8 1
wx 90 @ 10
/!x 00
'
EXPECT='0x0000000a hit0_0 90
90
'
run_test

NAME='cmd.hit for /!'
BROKEN=
FILE='malloc://1024'
CMDS='e cmd.hit = p8 1
w AAAAAAAAAAB
/! A
'
EXPECT='0x0000000a hit0_0 "AAAAAAAAAAB"
42
'
run_test

NAME='cmd.hit for /+'
BROKEN=
FILE='malloc://1024'
CMDS='e cmd.hit = p8 3
w ABCDEF
/+ ABC
'
EXPECT='0x00000000 hit0_0 414243
414243
'
run_test

NAME='cmd.hit for //'
BROKEN=
FILE='malloc://1024'
CMDS='e cmd.hit = p8 1
w AAAAAAAAAAB
/! A
//
'
EXPECT='0x0000000a hit0_0 "AAAAAAAAAAB"
42
0x0000000a hit1_0 "AAAAAAAAAAB"
42
'
run_test

NAME='cmd.hit for /h'
BROKEN=
FILE='malloc://1024'
BROKEN=1
CMDS='e cmd.hit = p8 1
e search.in =raw
/h md5 348a9791dc41b89796ec3808b5b5262f
'
EXPECT='f hash.md5.348a9791dc41b89796ec3808b5b5262f = 0x0
00
'
run_test

NAME='cmd.hit for /a'
FILE='malloc://1024'
ARGS=
BROKEN=
CMDS='e cmd.hit = pi 4
e asm.bits=32
"wa add esp,8;pop ebx; pop ebp; ret"
/a add esp, 8
'
EXPECT='0x00000000 hit0_0 83c408
add esp, 8
pop ebx
pop ebp
ret
'
run_test

NAME='cmd.hit for /A'
FILE='malloc://1024'
ARGS=
CMDS='e cmd.hit = pi 1
e asm.bits=32
"wa add esp,8;pop ebx; pop ebp; ret"
/A pop
'
EXPECT='0x00000003 1 pop ebx
pop ebx
0x00000004 1 pop ebp
pop ebp
'
run_test

NAME="cmd.hit for /bx"
FILE=malloc://1024
CMDS='e cmd.hit = p8 4
w ABCD @ 0x100
e search.from = 0x100
e search.to = 0x104
b 0x100
/bx 41424344
'
EXPECT='0x00000100 hit0_0 41424344
41424344
'
run_test

NAME='cmd.hit for /B'
FILE='malloc://1024'
ARGS=
CMDS='wx cffa edfe
e cmd.hit = px 1
e search.from = 0
e search.to = 0x10
/B
'
EXPECT='0x00000000  mach064
'
run_test

NAME='cmd.hit for /i'
BROKEN=
FILE='malloc://1024'
CMDS='e cmd.hit = ps
e search.from = 0
e search.to = 0x10
w AAAAAAAAAAB
/i aaaaaaaaaab
'
EXPECT='0x00000000 hit0_0 "AAAAAAAAAAB"
AAAAAAAAAAB
'
run_test

NAME='cmd.hit for /r from/to in range'
BROKEN=1
FILE='../bins/elf/analysis/ls-linux64'
CMDS='e cmd.hit = pi 1
e search.from = 0x00005c20
e search.to = 0x00005c49
/r sym.imp.__libc_start_main
'
EXPECT='(nofunc) 0x5c44 [call] call sym.imp.__libc_start_main
call sym.imp.__libc_start_main
'
run_test

NAME='from/to /r not in range'
BROKEN=1
FILE='../bins/elf/analysis/ls-linux64'
CMDS='e cmd.hit = pi 1
e search.from = 0x00005c20
e search.to = 0x00005c44
/r sym.imp.__cxa_finalize
'
EXPECT='
'
run_test

NAME='from/to /v'
BROKEN=
FILE='-'
CMDS='wx 01
e cmd.hit = pi 1
e search.in =raw
e search.from = 0x00000000
e search.to = 0x00000004
/v1 1
'
EXPECT='0x00000000 hit0_0 01
add dword [rax], eax
'
run_test

NAME='from/to /v not in range'
BROKEN=
FILE='-'
CMDS='wx 01
e cmd.hit = pi 1
e search.in =raw
e search.from = 0x00000000
e search.to = 0x00000000
/v1 1
'
EXPECT=''
run_test

NAME='from/to /V'
BROKEN=1
FILE='-'
CMDS='wx 05
e cmd.hit = pi 1
e search.in =raw
e search.from = 0x00000000
e search.to = 0x00000004
/V1 1 5
'
EXPECT='0x00000000 hit0_0 05
add dword [rax], eax
'
run_test

NAME='from/to /V not in range'
BROKEN=
FILE='-'
CMDS='wx 05
e cmd.hit = pi 1
e search.in =raw
e search.from = 0x00000000
e search.to = 0x00000000
/V1 1 5
'
EXPECT=''
run_test
