#!/bin/sh
# GPL 3+ - Copyright (C) 2012  pancake, Edd Barrett, Simon Ruderich
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='zs unset'
CMDS='
zs test1
za foo1 b aabbccdd
za bar1 b aabbccdd
zs test2
za foo2 b aabbccdd
za bar2 b aabbccdd
zs test3
za foo3 b aabbccdd
za bar3 b aabbccdd
zs *
zs-test2
z~foo1
z~bar1
z~foo2
z~bar2
z~foo3
z~bar3
'
EXPECT='(test1) foo1:
(test1) bar1:
foo2:
bar2:
(test3) foo3:
(test3) bar3:
'
run_test

NAME='zsr newname'
CMDS='
zs test1
za foo1 b aabbccdd
za bar1 b aabbccdd
zs test2
za foo2 b aabbccdd
za bar2 b aabbccdd
zs test3
za foo3 b aabbccdd
za bar3 b aabbccdd
zs test2
zsr newtest2
zs *
z~foo1
z~bar1
z~foo2
z~bar2
z~foo3
z~bar3
'
EXPECT='(test1) foo1:
(test1) bar1:
(newtest2) foo2:
(newtest2) bar2:
(test3) foo3:
(test3) bar3:
'
run_test

NAME='zsr newname (dupplicated name)'
CMDS='
zs test1
za foo1 b aabbccdd
za bar1 b aabbccdd
zs test2
za foo2 b aabbccdd
za bar2 b aabbccdd
zs test3
za foo3 b aabbccdd
za bar3 b aabbccdd
zs test2
zsr test1
zs *
z~foo1
z~bar1
z~foo2
z~bar2
z~foo3
z~bar3
'
EXPECT='(test1) foo1:
(test1) bar1:
(test2) foo2:
(test2) bar2:
(test3) foo3:
(test3) bar3:
'
run_test

NAME='zsr newname (root zs)'
CMDS='
zs test1
za foo1 b aabbccdd
za bar1 b aabbccdd
zs test2
za foo2 b aabbccdd
za bar2 b aabbccdd
zs test3
za foo3 b aabbccdd
za bar3 b aabbccdd
zs *
zsr newtest
z~foo1
z~bar1
z~foo2
z~bar2
z~foo3
z~bar3
'
EXPECT='(test1) foo1:
(test1) bar1:
(test2) foo2:
(test2) bar2:
(test3) foo3:
(test3) bar3:
'
run_test

NAME='z-'
CMDS='zs test
za foo b aa
zs test2
za foo b aa
za bar b bb
zs *
z-foo
z
zs test2
z-foo
z
zs *
z
zs-test
z
z-foo
z
'
EXPECT='(test2) foo:
  bytes: aa
(test2) bar:
  bytes: bb
(test) foo:
  bytes: aa
bar:
  bytes: bb
(test2) bar:
  bytes: bb
(test) foo:
  bytes: aa
foo:
  bytes: aa
(test2) bar:
  bytes: bb
(test2) bar:
  bytes: bb
'
run_test

NAME='z-*'
CMDS='
zs test1
za foo1 b aabbccdd
za bar1 b aabbccdd
zs test2
za foo2 b aabbccdd
za bar2 b aabbccdd
zs test3
za foo3 b aabbccdd
za bar3 b aabbccdd
zs test2
z-*
zs *
z~foo2
z~bar2
'
EXPECT=''
run_test

NAME='za b and binmasks'
CMDS='
za test b .abbc.dd..
z
'
EXPECT='test:
  bytes: .abbc.dd..
'
run_test

NAME='za b zero mask'
CMDS='
za test b ....
z
'
EXPECT=''
run_test

NAME='za b + z/'
FILE=../bins/elf/analysis/go_stripped
CMDS='
za sym.fmt.Println b 653b2530000000724b53b834e7150883ec188b15401c22088d4c24048b5c242083ec08ff742434ff742434ff742434525051e829ffffff8b44242089038b4424248943048b44242889430889d883c4345bc204006a106a1ce85e350700c20400
z/
?v sign.bytes.sym.fmt.Println_0
'
EXPECT='0x805b030
'
run_test

NAME='za a + z/'
FILE=../bins/elf/analysis/go_stripped
CMDS='
za sym.fmt.Println a 653b2530000000724b53b834e7150883ec188b15401c22088d4c24048b5c242083ec08ff742434ff742434ff742434525051e829ffffff8b44242089038b4424248943048b44242889430889d883c4345bc204006a106a1ce85e350700c20400
z/
?v sign.bytes.sym.fmt.Println_1
'
EXPECT='0x805b030
'
run_test

NAME='z/ with search.in'
FILE=../bins/elf/analysis/go_stripped
CMDS='
za date_string b 323030362d30312d30322031353a30343a30352e393939393939393939202d30373030204d535400
za sym.fmt.Println b 653b2530000000724b53b834e7150883ec188b15401c22088d4c24048b5c242083ec08ff742434ff742434ff742434525051e829ffffff8b44242089038b4424248943048b44242889430889d883c4345bc204006a106a1ce85e350700c20400
fs sign
f~?
e search.in=file
z/
?v sign.bytes.date_string_0
?v sign.bytes.sym.fmt.Println_0
f-*
f~?
e search.in=io.sections.exec
z/
?v sign.bytes.elf_header_0
?v sign.bytes.sym.fmt.Println_0
'
EXPECT='0
0x81a5898
0x805b030
0
0x0
0x805b030
'
run_test

NAME='z/ with search.align'
FILE=malloc://1024
CMDS='
wx 00112233445566778899aabbccddeeff
za foo b 1122
fs *
e search.align=2
z/
f~?
e search.align=1
z/
f~?
'
EXPECT='0
1
'
run_test

NAME='z/ with search.{from, to}'
FILE=malloc://1024
CMDS='
wx 00112233445566778899aabbccddeeff
za a b 11223344
za b b bbccddee
fs *
f~?
e search.in=raw
e search.from=0x0
e search.to=0x8
z/
?v sign.bytes.a_0
?v sign.bytes.b_0
f-*
f~?
e search.from=0x8
e search.to=0xf
z/
?v sign.bytes.a_0
?v sign.bytes.b_0
'
EXPECT='0
0x1
0x0
0
0x0
0xb
'
run_test

NAME='za b ; z/ ; aa ; axt'
FILE=../bins/elf/analysis/zigs_stripped
CMDS='
za sym.print b 5548....48......48......48......48....bf........b8........e8........90c9c3
z/
e anal.hasnext=0
aa
axt 0x400536
'
EXPECT='call 0x40056f call sign.bytes.sym.print_0 in main
'
run_test

NAME='zaf'
FILE=../bins/elf/analysis/zigs
CMDS='
aaa
zs zigs
zaf sym.main
z
'
EXPECT='zigs.sym.main:
  bytes: 554889e54883ec1089....48......bf........e8........b800000000c9c3
  graph: cc=1 nbbs=1 edges=0 ebbs=1
  offset: 0x0040055b
  refs: sym.print
'
run_test


NAME='zaf at offset'
FILE=../bins/elf/analysis/zigs
CMDS='
aaa
zs zigs
zaf @ sym.main
z
'
EXPECT='zigs.sym.main:
  bytes: 554889e54883ec1089....48......bf........e8........b800000000c9c3
  graph: cc=1 nbbs=1 edges=0 ebbs=1
  offset: 0x0040055b
  refs: sym.print
'
run_test

NAME='zaf (root zignspace)'
FILE=../bins/elf/analysis/zigs
CMDS='
aaa
zaf sym.main
z
'
EXPECT='sym.main:
  bytes: 554889e54883ec1089....48......bf........e8........b800000000c9c3
  graph: cc=1 nbbs=1 edges=0 ebbs=1
  offset: 0x0040055b
  refs: sym.print
'
run_test

NAME='zaf zigname'
FILE=../bins/elf/analysis/zigs
CMDS='
aaa
zs zigs
zaf sym.main foobar
z
'
EXPECT='foobar:
  bytes: 554889e54883ec1089....48......bf........e8........b800000000c9c3
  graph: cc=1 nbbs=1 edges=0 ebbs=1
  offset: 0x0040055b
  refs: sym.print
'
run_test

NAME='zaf zigname (root zignspace)'
FILE=../bins/elf/analysis/zigs
CMDS='
aaa
zaf sym.main foobar
z
'
EXPECT='foobar:
  bytes: 554889e54883ec1089....48......bf........e8........b800000000c9c3
  graph: cc=1 nbbs=1 edges=0 ebbs=1
  offset: 0x0040055b
  refs: sym.print
'
run_test

NAME='zs + zaf + z/'
FILE=../bins/elf/analysis/zigs
CMDS='
aaa
zs zigs
zaf sym.main
z/
?v sign.bytes.zigs.sym.main_0
'
EXPECT='0x40055b
'
run_test

NAME='zs + zaf + z/'
FILE=../bins/elf/analysis/zigs
CMDS='
aaa
zaf sym.main
z/
?v sign.bytes.sym.main_0
'
EXPECT='0x40055b
'
run_test

NAME='zs + zaf zigname + z/'
FILE=../bins/elf/analysis/zigs
CMDS='
aaa
zaf sym.main foobar
z/
?v sign.bytes.foobar_0
'
EXPECT='0x40055b
'
run_test

NAME='zc'
FILE=../bins/elf/analysis/zigs_stripped
CMDS='
aa
za sym.print b 5548....48......48......48......48....bf........b8........e8........90c9c3
zc @@ fcn*
?v sign.bytes.sym.print_0
'
EXPECT='0x400536
'
run_test

NAME='zc graph zign'
FILE=../bins/elf/analysis/zigs_stripped
CMDS='
aa
za sym.print g cc=1 nbbs=1 edges=0 ebbs=1
zc @@ fcn*
?v sign.graph.sym.print_0
'
EXPECT='0x400536
'
run_test

NAME='z/ graph zign'
FILE=../bins/elf/analysis/zigs_stripped
CMDS='
aa
za sym.print_metric g cc=1 nbbs=1 edges=0 ebbs=1
z/
?v sign.graph.sym.print_metric_2
'
EXPECT='0x400536
'
run_test

NAME='z/ bytes + graph zign'
FILE=../bins/elf/analysis/zigs_stripped
CMDS='
aa
za sym.print b 5548....48......48......48......48....bf........b8........e8........90c9c3
za sym.print g cc=1 nbbs=1 edges=0 ebbs=1
z/
?v sign.bytes.sym.print_0
?v sign.graph.sym.print_2
'
EXPECT='0x400536
0x400536
'
run_test

NAME='z/ + zign.match.{bytes, graph}'
FILE=../bins/elf/analysis/zigs_stripped
CMDS='
aa
za sym.print b 5548....48......48......48......48....bf........b8........e8........90c9c3
za sym.print g cc=1 nbbs=1 edges=0 ebbs=1
fs sign
e zign.match.bytes = true
e zign.match.graph = false
z/
f~sign.bytes.sym.print?
f~sign.graph.sym.print?
f-*
e zign.match.bytes = false
e zign.match.graph = true
z/
f~sign.bytes.sym.print?
f~sign.graph.sym.print?
'
EXPECT='1
0
0
3
'
run_test

NAME='zc + zign.match.{bytes, graph}'
FILE=../bins/elf/analysis/zigs_stripped
CMDS='
aa
za sym.print b 5548....48......48......48......48....bf........b8........e8........90c9c3
za sym.print g cc=1 nbbs=1 edges=0 ebbs=1
fs sign
e zign.match.bytes = true
e zign.match.graph = false
zc @ 0x400536
f~sign.bytes.sym.print?
f~sign.graph.sym.print?
f-*
e zign.match.bytes = false
e zign.match.graph = true
zc @ 0x400536
f~sign.bytes.sym.print?
f~sign.graph.sym.print?
'
EXPECT='1
0
0
1
'
run_test

NAME='aa ; zfs libc.sig'
FILE=../bins/elf/analysis/pid_stripped
ARGS=
CMDS="aa ; zfs ../bins/other/sigs/libc.sig"
EXPECT='Found flirt.__libc_start_main
'
run_test

NAME='zfd libc.sig'
FILE=../bins/elf/analysis/pid_stripped
ARGS=
CMDS="zfd ../bins/other/sigs/libc.sig"
EXPECT='41564155B8........4154554D89C4534889CD4D89CD4881EC900000004885C0:
 0. 16 D2A2 0298 0000:__libc_start_main
'
run_test

NAME='af ; af ; zfs libc.sig'
FILE=../bins/elf/analysis/pid_stripped
ARGS=
CMDS="s 0x4e2420 ; af ; s 0x4e25c7 ; af ; zfs ../bins/other/sigs/libc.sig ; afl ~4e2420"
EXPECT='0x004e2420   40 664          flirt.__libc_start_main
'
run_test
