#!/bin/sh
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='pif invalid instruction'
FILE=../bins/elf/mentalminer
ARGS='-A -B 0x555555554000'
BROKEN=1
CMDS='
e asm.functions = false
e asm.flags = false
e asm.comments = false
e asm.calls = false
aaa
s sym.parse__IO_FILE__
pif~?
'
EXPECT='1367
'
run_test

NAME='pif invalid instruction'
FILE=../bins/elf/mentalminer
ARGS='-A -B 0x555555554000'
BROKEN=
CMDS='
e asm.functions = false
e asm.flags = false
e asm.comments = false
e asm.calls = false
aaa
pif~?
'
EXPECT='11
'
run_test