#!/bin/sh
# GPL 3+ - Copyright (C) 2017  pancake
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

# "!" - run commands (via system)

NAME='/ search.in=io.maps without -m'
FILE='../bins//wasm/inc.wast'
ARGS="-m 0x80000"
BROKEN=
CMDS='
e search.in=io.maps
e io.va=true
/ get~[0]
'
EXPECT='0x00080053
0x00080067
'
run_test

NAME='/ search.in=io.maps without -m'
FILE='../bins//wasm/inc.wast'
ARGS=""
BROKEN=
CMDS='
e search.in=io.maps
/ get~[0]
'
EXPECT='0x00000053
0x00000067
'
run_test

NAME='/ search.in=(default)'
FILE='../bins//wasm/inc.wast'
ARGS=""
BROKEN=
CMDS='
/ get~[0]
'
EXPECT='0x00000053
0x00000067
'
run_test

NAME='/ search.in=file'
FILE='../bins//wasm/inc.wast'
ARGS=""
BROKEN=
CMDS='
e search.in=file
/ get~[0]
'
EXPECT='0x00000053
0x00000067
'
run_test

NAME='/ search io.maps with map'
FILE='../bins//wasm/inc.wast'
ARGS="-m 0x80000"
BROKEN=
CMDS='
e search.in=io.maps
e io.va=true
/ get~[0]
'
EXPECT='0x00080053
0x00080067
'
run_test

NAME='/ search io.maps 2'
FILE='../bins//wasm/inc.wast'
ARGS="-m 0x80000"
BROKEN=
CMDS='
om ../bins/wasm/inc.wast 0x400000
e io.va=true
e search.in=io.maps
/ get~[0]
'
EXPECT='0x00080053
0x00080067
0x00400053
0x00400067
'
run_test
