#!/bin/sh
# GPL 3+ - Copyright (C) 2017 Maijin
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='pdc @ main ioli0x0'
FILE=../bins/elf/ioli/crackme0x00
ARGS=''
BROKEN=
CMDS='
aaa
pdc @ main~str.250382
pdc @ main~strcmp
'
EXPECT='       dword [local_4h] = "250382" //[0x804858f:4]=0x33303532 ; str.250382 
       int strcmp(const char * s1 : (*0x177fe4)0x00177fb4 =, const char * s2 : (*0x804858f)0x00177fb8 = 250382)
'
run_test

