#!/bin/sh
# GPL 3+ - Copyright (C) 2012  pancake, Edd Barrett, Simon Ruderich
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='visual intermediate'
BROKEN=1
FILE=../bins/elf/analysis/main
CMDS='Vpjjjjdi
d
qah*
'
EXPECT='ahi 10 @ 0x400419
'
run_test

NAME='V&q change bits'
FILE=../bins/elf/ioli/crackme0x00
ARGS=
CMDS='
e scr.interactive=true
V&q
af
pi 1
V&q
pi 1
'
EXPECT='xor ebp, ebp
xor bp, bp
'
run_test

NAME='V - crash #1'
FILE='-'
CMDS='V|||'
run_test

NAME='V - crash #2'
FILE='-'
CMDS='V```...'
run_test
