#!/bin/sh
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='asm.describe alignment with memory access'
FILE=-
CMDS='
e asm.arch = x86
e anal.arch = x86
e asm.bits=32
"wa mov eax, [0x100]"
e asm.describe = true
pd 1
'
EXPECT='            0x00000000      a100010000     mov eax, dword [0x100]      ; [0x100:4]=0 ; moves data from src to dst
'
run_test


NAME='asm.describe alignment'
FILE=-
CMDS='
wa nop
e asm.describe = true
pd 1
'
EXPECT='            0x00000000      90             nop                         ; no operation
'
run_test
