#!/bin/sh
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

FILE=malloc://1024
NAME="Cs"
CMDS='
w hello world
Cs @ $$
C*~[1]
'
EXPECT='12
'
run_test

FILE=malloc://1024
NAME="Cs 5"
CMDS='
w hello world
Cs 5
C*~[1]
'
EXPECT='5
'
run_test

FILE=malloc://1024
NAME="Cz"
CMDS='
w hello world
Cz
C*~[1]
'
EXPECT='12
'
run_test

FILE=malloc://1024
NAME="Cd : data"
CMDS='
e asm.arch=x86
e asm.bits=32
w 909090
Cd 3
pd 2
'
EXPECT='            0x00000000 hex length=3 delta=0
0x00000000  3930 39                                  909

            0x00000003      3039           xor byte [ecx], bh
'
run_test

FILE=malloc://1024
NAME="Cd : data + align"
BROKEN=1
CMDS='
e asm.arch=x86
e asm.bits=32
w 909090
Cd 3
s 1
pd 2
'
EXPECT='            0x00000001 hex length=3 delta=1
0x00000001  30 39                                    09

            0x00000003      3039           xor byte [ecx], bh
'
run_test

FILE=malloc://1024
NAME="Cs : convert to string"
CMDS='
w hello
Cs 6
pd 1
'
EXPECT='            0x00000000     .string "hello" ; len=6
'
run_test

FILE=malloc://1024
NAME="Cs : concatenated strings bug"
BROKEN=
CMDS='
w hello\x00world
e asm.linesup=0
Cs 6
Cs 6@6
pd 2
'
EXPECT='            0x00000000     .string "hello" ; len=6
            0x00000006     .string "world" ; len=6
'
run_test


FILE=malloc://1024
NAME="Cs : concatenated strings bug"
BROKEN=
CMDS='
w hello\x00world
e asm.linesup=0
Cs 6
Cs 6@6
pd 2
'
EXPECT='            0x00000000     .string "hello" ; len=6
            0x00000006     .string "world" ; len=6
'
run_test

FILE=malloc://128
NAME="Cs : string count bug"
CMDS='
w hello
Cs 6
C*~?
'
EXPECT='1
'
run_test

FILE=malloc://128
NAME="Ch : hide bytes in pd"
CMDS='
e scr.color=false
wx 554889e54883c768
Ch 2
pd 2
Ch-
'
EXPECT='            0x00000000 (2 bytes hidden)
            0x00000002      89e5           mov ebp, esp
'
run_test

FILE=malloc://1024
NAME="Ch : add/del hide bytes"
CMDS='
e scr.color=false
wx 554889e54883c768
Ch 2@0x100
C*~?
Ch-@0x100
C*~?
'
EXPECT='1
0
'
run_test

NAME="Cf should be silent"
FILE=-
ARGS=
CMDS='Cf 32 2xx
'
EXPECT=''
run_test

NAME="format memory metadata"
FILE=-
ARGS=
CMDS='wx 41424344
Cf 4 x
pd 1
'
EXPECT='            0x00000000 format x {
0x00000000 = 0x44434241
} 4
'
run_test

NAME="arm1.bin dword pointers with Cd"
FILE=../bins/elf/arm1.bin
ARGS=
CMDS='s 0xdb98
Cd 4[3]
pd 3
'
EXPECT='            ;-- $d:
            0x0000db98      .dword 0x00085038 ; obj.main_arena
            0x0000db9c      .dword 0x000844ac ; obj.check_action
            0x0000dba0      .dword 0x000663c4 ; str.free__:_invalid_pointer
'
run_test

NAME="arm1.bin dword pointers with Cd and ahi 1"
FILE=../bins/elf/arm1.bin
ARGS=
CMDS='s 0xdb98
Cd 4[3]
ahi 1
pd 3
'
EXPECT='            ;-- $d:
            0x0000db98      .int32 00111000010100000000100000000000b ; obj.main_arena
            0x0000db9c      .dword 0x000844ac ; obj.check_action
            0x0000dba0      .dword 0x000663c4 ; str.free__:_invalid_pointer
'
run_test

NAME="arm1.bin dword pointers with Cd and ahi 8"
FILE=../bins/elf/arm1.bin
ARGS=
CMDS='s 0xdb98
Cd 4[3]
ahi 8
pd 3
'
EXPECT='            ;-- $d:
            0x0000db98      .int32 2050070o ; obj.main_arena
            0x0000db9c      .dword 0x000844ac ; obj.check_action
            0x0000dba0      .dword 0x000663c4 ; str.free__:_invalid_pointer
'
run_test

NAME="arm1.bin dword pointers with Cd and ahi 10"
FILE=../bins/elf/arm1.bin
ARGS=
CMDS='s 0xdb98
Cd 4[3]
ahi 10
pd 3
'
EXPECT='            ;-- $d:
            0x0000db98      .int32 544824 ; obj.main_arena
            0x0000db9c      .dword 0x000844ac ; obj.check_action
            0x0000dba0      .dword 0x000663c4 ; str.free__:_invalid_pointer
'
run_test

NAME="arm1.bin dword pointers with Cd and ahi 16"
FILE=../bins/elf/arm1.bin
ARGS=
CMDS='s 0xdb98
Cd 4[3]
ahi 16
pd 3
'
EXPECT='            ;-- $d:
            0x0000db98      .dword 0x00085038 ; obj.main_arena
            0x0000db9c      .dword 0x000844ac ; obj.check_action
            0x0000dba0      .dword 0x000663c4 ; str.free__:_invalid_pointer
'
run_test

NAME="Ch and CCu on instr with potential LEA cmt"
FILE=../bins/pe/ConsoleApplication1.exe
ARGS=
CMDS='Ch 6 @ 0x004010fa
CCu get error @ 0x004010fa
pd 1 @ 0x004010fa
'
EXPECT='            0x004010fa (6 bytes hidden)                                ; get error
'
run_test

NAME="C[Chsdmf][*j] without arguments"
FILE=malloc://1024
ARGS=
CMDS='k anal/meta/range.0x5=0x5120
w hello world
Cs @ $$
s 0x100
e asm.arch=x86
e asm.bits=32
w 909090
Cd 3
s 0x200
wx 554889e54883c768
Ch 2
s 0x300
wx 41424344
Cf 4 x
s 0x0
CCu Hello!
s 0x380
wx cafebabe00000032
Cm 8 wwww
Cs
?e ----
Cd
?e ----
Ch
?e ----
Cf
?e ----
CC
?e ----
Cm
?e ----
C
?e ----
Cs*
?e ----
Cd*
?e ----
Ch*
?e ----
Cf*
?e ----
CC*
?e ----
Cm*
?e ----
C*
?e ----
Csj
?e ----
Cdj
?e ----
Chj
?e ----
Cfj
?e ----
CCj
?e ----
Cmj
?e ----
Cj
'
EXPECT='0x00000000 ascii[12] "hello world"
----
0x00000100 data Cd 3
----
0x00000200 hidden Ch 2
----
0x00000300 format 4 x
----
0x00000000 CCu "Hello!"
----
0x00000380 magic 8 wwww
----
0x00000000 CCu "Hello!"
0x00000100 data Cd 3
0x00000300 format 4 x
0x00000200 hidden Ch 2
0x00000380 magic 8 wwww
0x00000000 ascii[12] "hello world"
----
Cs 12 @ 0x00000000 # hello world
----
Cd 3 @ 0x00000100
----
Ch 2 @ 0x00000200
----
Cf 4 x @ 0x00000300
----
CCu base64:SGVsbG8h @ 0x00000000
----
Cm 8 wwww @ 0x00000380
----
CCu base64:SGVsbG8h @ 0x00000000
Cd 3 @ 0x00000100
Cf 4 x @ 0x00000300
Ch 2 @ 0x00000200
Cm 8 wwww @ 0x00000380
Cs 12 @ 0x00000000 # hello world
----
[{"offset":0, "type":"Cs", "name":"aGVsbG8gd29ybGQ=", "enc":"latin1", "ascii":true}]
----
[{"offset":256, "type":"Cd", "name":"3"}]
----
[{"offset":512, "type":"Ch", "name":"2"}]
----
[{"offset":768, "type":"Cf", "name":"x"}]
----
[{"offset":0, "type":"CCu", "name":"Hello!"}]
----
[{"offset":896, "type":"Cm", "name":"wwww"}]
----
[{"offset":0, "type":"CCu", "name":"Hello!"},{"offset":256, "type":"Cd", "name":"3"},{"offset":768, "type":"Cf", "name":"x"},{"offset":512, "type":"Ch", "name":"2"},{"offset":896, "type":"Cm", "name":"wwww"},{"offset":0, "type":"Cs", "name":"aGVsbG8gd29ybGQ=", "enc":"latin1", "ascii":true}]
'
run_test

NAME="Cs ascii/latin1"
FILE=../bins/pe/testapp-msvc64.exe
ARGS=
CMDS='Cs @ 0x1400160a0
Cs~gate
Cs~ANSI
'
EXPECT='0x1400160a0 latin1[18] "latin1 gate: \xce\xbb\xab\xce"
0x1400160b8 ascii[50] "  -- in ConEmu, run `chcp 28591` to see the gate."
0x140016000 ascii[19] "\tANSI\esc: \e[33m\r\n"
'
run_test

NAME="Csj ascii/latin1"
FILE=../bins/pe/testapp-msvc64.exe
ARGS=
CMDS='Cs @ 0x1400160a0
Csj
'
FILTER='grep -o "{[^}]*\(5368799392\|5368799416\),[^}]*}"'
EXPECT='{"offset":5368799392, "type":"Cs", "name":"bGF0aW4xIGdhdGU6IM67q84=", "enc":"latin1", "ascii":false}
{"offset":5368799416, "type":"Cs", "name":"ICAtLSBpbiBDb25FbXUsIHJ1biBgY2hjcCAyODU5MWAgdG8gc2VlIHRoZSBnYXRlLg==", "enc":"latin1", "ascii":true}
'
run_test
