#!/bin/sh
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

FILE=../bins/elf/analysis/x86-simple
CMDS='
p8 10 @ 0x8048065
'
EXPECT='5bb801000000bb2a0000
'
EXPECT_ERR=''

run_test

NAME='display mapped flag in sections list'
FILE=../bins/elf/analysis/x86-simple
CMDS='S
'
EXPECT='[00:00] * pa=0x00000000 mr-x va=0x08048000 sz=0x0072 vsz=0x0072 LOAD0
'
EXPECT_ERR=''

run_test
