#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

test_vector() {
NAME="${PLUGIN} ${BITS}: [${2}]"
if [ "${4}" = "br" ]; then
    BROKEN=1
fi
CMDS='!rasm2 -a '${1}' -b '${BITS}' "'${2}'"
'
if [ "${IGNORE_ERR}" = 1 ]; then
EXPECT="${3}
"
else
EXPECT_ERR="${3}
"
fi
run_test
}

test_invalid() {
IGNORE_ERR=0
test_vector "${1}" "${2}" "Cannot assemble '${2}' at line 3
invalid"
}

PLUGIN=arm
BITS=16

# Expected to fail
test_invalid "${PLUGIN}" "b gh"
test_invalid "${PLUGIN}" "lsr r15, r5, 2"
test_invalid "${PLUGIN}" "lsr r2, r15, 2"
test_invalid "${PLUGIN}" "lsr r2, r5, 33"
